### PR TITLE
Fixing series fold

### LINKED ISSUE #79: Running `fold` to perform a row sum gives an error code `DateExpected`.
#### Have you tried latest version of polars?

- [yes]✓
- [no]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?
0.7.4

#### What operating system are you using polars on?
macOS

#### What node version are you using
20.3.0

#### Describe your bug.

Running `fold` to perform a row sum gives an error code `DateExpected`.

#### What are the steps to reproduce the behavior?

```js
import('nodejs-polars').then(mod => {pl = mod})
df = pl.DataFrame({
    "a": [1, 2, 3],
    "b": [1, 2, 3],
    "c": [1, 2, 3]
});
df.fold((s1, s2) => s1.plus(s2))
```

#### What is the actual behavior?

```js
Uncaught Error
    at dtypeWrap (xxx/node_modules/nodejs-polars/bin/series/index.js:29:65)
    at Proxy.plus (xxx/node_modules/nodejs-polars/bin/series/index.js:428:20)
    at REPL3:1:24
    at xxx/node_modules/nodejs-polars/bin/dataframe.js:166:60
    at Array.reduce (<anonymous>)
    at Proxy.fold (xxx/node_modules/nodejs-polars/bin/dataframe.js:166:38) {
  code: 'DateExpected'
}
```

#### What is the expected behavior?

```js
Series: 'a' [f64]
[
    3
    6
    9
]
```

### PR DESCRIPTION
**Pull request by Bidek56**
Fixing series fold to close #79

### CODE REVIEW

File: polars/series/index.ts [hunk 1]
```diff
@@ -1528,16 +1531,20 @@ export function _Series(_s: any): Series {
       return this.length;
     },
     lt(field) {
-      return dtypeWrap("Lt", field);
+      if (typeof field === "number") return dtypeWrap("Lt", field);
+      return wraps("lt", field);
```
Comment (universalmind303) [inline polars/series/index.ts:1535]: the extra method seems unnecessary, also shouldn't we check that this is a Series

```ts
    if (typeof field === "number") {
        return dtypeWrap("Lt", field);
    }
    else if (Series.isSeries(field)) {
        return wrap("Lt", field._s)
    } else {
        throw new Error()
    }
```

Comment (Bidek56) [reply polars/series/index.ts:1535]: I was not sure how to handle `...args` and `args` in one func without throwing a TS error.
We could check if it's a Series, but I think that's implied by default.

Comment (Bidek56) [reply polars/series/index.ts:1535]: Would this be better? `return wrap("lt", (field as any)._s);`
